name = "Invariants"
uuid = "115d0255-0791-41d2-b533-80bc4cbe6c10"
authors = ["lorenzoh <lorenz.ohly@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
InlineTest = "bd334432-b1e7-49c7-a2dc-dd9149e4ebd6"
InvariantsCore = "69cbffe8-09de-43b1-81db-93034495284f"
TextWrap = "b718987f-49a8-5099-9789-dcd902bef87d"

[compat]
AbstractTrees = "0.4"
InlineTest = "0.2"
InvariantsCore = "0.1"
TextWrap = "1"
julia = "1"

[pollen]
title = "Invariants.jl"
url = "https://github.com/lorenzoh/Invariants.jl"
