name = "Invariants"
uuid = "115d0255-0791-41d2-b533-80bc4cbe6c10"
authors = ["lorenzoh <lorenz.ohly@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ANSIColoredPrinters = "a4c015fc-c6ff-483c-b24f-f7ea428134e9"
InlineTest = "bd334432-b1e7-49c7-a2dc-dd9149e4ebd6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
TextWrap = "b718987f-49a8-5099-9789-dcd902bef87d"

[compat]
julia = "1"


[pollen]
title = "Invariants.jl"
url = "https://github.com/lorenzoh/Invariants.jl"