name = "InvariantsCore"
uuid = "69cbffe8-09de-43b1-81db-93034495284f"
authors = ["lorenzoh <lorenz.ohly@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "1"
